### PR TITLE
Create setup folder

### PR DESCRIPTION
**Pull request by Jvr2022**

### CODE REVIEW

**Comment by xanonDev** [comment]
I think it's a very good idea, but the template folder would also have to be moved there for it to work, so I don't know if it wouldn't be better to make the src folder and put the setup files and pinkcord code there

**Comment by Jvr2022** [comment]
I create a scr folder soon

**Comment by xanonDev** [comment]
I can do it when I get home in half an hour

**Comment by Jvr2022** [comment]
okay i actually have to go home too

**Comment by Jvr2022** [comment]
I think I'll be home in 45 minutes

**Pull request closed without merging**
