### PR TITLE
Add a python installation

### PR DESCRIPTION
**Pull request by Jvr2022**

### CODE REVIEW

**Comment by xanonDev** [comment]
error when running the script
: was unexpected at this time.

**Comment by Jvr2022** [comment]
I look later i am now not at home

**Comment by Jvr2022** [comment]
I think this wil be fix the error

**Comment by Jvr2022** [comment]
So u look?

**Comment by Jvr2022** [comment]
I am trying it to but its dificult

**Comment by Jvr2022** [comment]
i am online i am trying to fix it @xanonDev

**Comment by Jvr2022** [comment]
i have fixed it

**Comment by Jvr2022** [comment]
i had founded a litle bug i am unstalling python to check if the bug is not anymore in the script

**Comment by Jvr2022** [comment]
The bug ie fixed and there is now a another bug with checking

**Comment by xanonDev** [comment]
good luck fixing it

**Comment by Jvr2022** [comment]
Can u friend me in discord my name is jvr2022

**Comment by xanonDev** [comment]
yes i can , my name is x__anon

**Comment by Jvr2022** [comment]
i am still working at it

**Comment by Jvr2022** [comment]
but can u contact me with discord?

**Pull request closed without merging**
